//-------------------------------------------------------
// Autogenerated from 'turretsystem_flame_turret.vmf'
//-------------------------------------------------------
TurretsystemFlameTurret <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.flame_turret_traverse,
			EntityGroup.SpawnTables.flame_turret_gun,
			EntityGroup.SpawnTables.flame_turret_base,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.flame_turret_muzzleflash,
			EntityGroup.SpawnTables.flame_turret_traverse,
			EntityGroup.SpawnTables.flame_turret_gun,
			EntityGroup.SpawnTables.flame_turret_comp_use,
			EntityGroup.SpawnTables.flame_turret_hurt1,
			EntityGroup.SpawnTables.flame_turret_hurt,
			EntityGroup.SpawnTables.flame_turret_sound,
			EntityGroup.SpawnTables.flame_turret_base,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			flame_turret_traverse = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/flame_turret_traverse.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flame_turret_traverse"
					origin = Vector( 0, 0, 39.5 )
				}
			}
			flame_turret_gun = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/flame_turret_gun.mdl"
					parentname = "flame_turret_traverse"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flame_turret_gun"
					vscripts = "turretsystem_turret_flame"
					origin = Vector( 0, 0, 44.9 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "flame_turret_hurtKill0-1"
							cmd2 = "flame_turret_soundKill0-1"
							cmd3 = "flame_turret_traverseKill0-1"
							cmd4 = "flame_turret_baseKill0-1"
							cmd5 = "flame_turret_muzzleflashKill0-1"
							cmd6 = "!selfKill0-1"
							cmd7 = "flame_turret_comp_useKill0-1"
						}
					}
				}
			}
			flame_turret_base = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/flame_turret_base.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flame_turret_base"
					origin = Vector( 0, 0, 0 )
				}
			}
			flame_turret_muzzleflash = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 30, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fire_jet_01"
					parentname = "flame_turret_gun"
					render_in_front = "0"
					start_active = "0"
					targetname = "flame_turret_muzzleflash"
					origin = Vector( 64, 1, 44.25 )
				}
			}
			flame_turret_comp_use = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "flame_turret_gun"
					origin = Vector( 3.72, 14.87, 8.25 )
					targetname = "flame_turret_comp_use"
					vscripts = "usetargets/turretsystem_turret_flame_comp"
				}
			}
			flame_turret_hurt = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_hurt"
					damage = "15"
					damagecap = "20"
					damagemodel = "0"
					damagetype = "8"
					nodmgforce = "1"
					origin = Vector( 64, 0, 48 )
					parentname = "flame_turret_gun"
					spawnflags = "67"
					StartDisabled = "1"
					targetname = "flame_turret_hurt"
					thinkalways = "1"
					extent = Vector( 48, 24, 24 )
				}
			}
			flame_turret_hurt1 = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_hurt"
					damage = "7"
					damagecap = "20"
					damagemodel = "0"
					damagetype = "8"
					nodmgforce = "1"
					origin = Vector( 140, 0, 56 )
					parentname = "flame_turret_gun"
					spawnflags = "67"
					StartDisabled = "1"
					targetname = "flame_turret_hurt"
					thinkalways = "1"
					extent = Vector( 20, 24, 32 )
				}
			}
			flame_turret_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "ambient/atmosphere/firewerks_stage_pyro_01.wav"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "flame_turret_gun"
					spawnflags = "48"
					targetname = "flame_turret_sound"
					origin = Vector( 32, -11.413, 9.25003 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // TurretsystemFlameTurret

RegisterEntityGroup( "TurretsystemFlameTurret", TurretsystemFlameTurret )
