//-------------------------------------------------------
// Autogenerated from 'turretsystem_laser_turret.vmf'
//-------------------------------------------------------
TurretsystemLaserTurret <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.laser_turret_traverse,
			EntityGroup.SpawnTables.laser_turret_gun,
			EntityGroup.SpawnTables.laser_turret_base,
			EntityGroup.SpawnTables.laser_turret_muzzleflash,
			EntityGroup.SpawnTables.laser_turret_comp,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.laser_turret_comp_use,
			EntityGroup.SpawnTables.laser_turret_beam_target,
			EntityGroup.SpawnTables.laser_turret_gun,
			EntityGroup.SpawnTables.laser_turret_muzzleflash,
			EntityGroup.SpawnTables.laser_turret_beam,
			EntityGroup.SpawnTables.laser_turret_comp,
			EntityGroup.SpawnTables.laser_turret_heattexture,
			EntityGroup.SpawnTables.laser_turret_traverse,
			EntityGroup.SpawnTables.laser_turret_base,
			EntityGroup.SpawnTables.laser_turret_heat_effect,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			laser_turret_traverse = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/laser_turret_traverse.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "laser_turret_traverse"
					origin = Vector( 0, 0, 40 )
				}
			}
			laser_turret_gun = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/laser_turret_gun.mdl"
					parentname = "laser_turret_traverse"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "laser_turret_gun"
					vscripts = "turretsystem_turret_laser"
					origin = Vector( -3, 0, 49 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "laser_turret_beamKill0-1"
							cmd2 = "laser_turret_traverseKill0-1"
							cmd3 = "laser_turret_baseKill0-1"
							cmd4 = "laser_turret_heattextureKill0-1"
							cmd5 = "laser_turret_beam_targetKill0-1"
							cmd6 = "laser_turret_muzzleflashKill0-1"
							cmd7 = "!selfKill0-1"
							cmd8 = "laser_turret_comp_useKill0-1"
							cmd9 = "laser_turret_compKill0-1"
							cmd10 = "laser_turret_heat_effectKill0-1"
						}
					}
				}
			}
			laser_turret_beam = 
			{
				SpawnInfo =
				{
					classname = "env_laser"
					damage = "100"
					dissolvetype = "None"
					EndSprite = "sprites/redglow3.vmt"
					framestart = "0"
					LaserTarget = "laser_turret_beam_target"
					NoiseAmplitude = "0"
					parentname = "laser_turret_gun"
					renderamt = "25"
					rendercolor = "255 0 0"
					renderfx = "11"
					spawnflags = "96"
					targetname = "laser_turret_beam"
					texture = "sprites/laserbeam.vmt"
					TextureScroll = "35"
					width = "0.25"
					origin = Vector( 19, 0, 49 )
				}
			}
			laser_turret_base = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/laser_turret_base.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "laser_turret_base"
					origin = Vector( 0, 0, 0 )
				}
			}
			laser_turret_muzzleflash = 
			{
				SpawnInfo =
				{
					classname = "env_sprite"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					framerate = "10.0"
					GlowProxySize = "1.0"
					HDRColorScale = "0.7"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "sprites/redglow3.vmt"
					parentname = "laser_turret_gun"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "9"
					spawnflags = "0"
					targetname = "laser_turret_muzzleflash"
					origin = Vector( 19, 0, 49 )
				}
			}
			laser_turret_comp = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 340, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "32"
					glowstate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/laptop/laptop.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "3"
					solid = "6"
					targetname = "laser_turret_comp"
					origin = Vector( -13, 10, 0 )
				}
			}
			laser_turret_comp_use = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "laser_turret_comp"
					origin = Vector( 8, 24, 8.25 )
					targetname = "laser_turret_comp_use"
					vscripts = "usetargets/turretsystem_turret_laser_comp"
				}
			}
			laser_turret_beam_target = 
			{
				SpawnInfo =
				{
					classname = "info_target_instructor_hint"
					parentname = "laser_turret_gun"
					targetname = "laser_turret_beam_target"
					origin = Vector( 797, 0, 49 )
				}
			}
			laser_turret_heattexture = 
			{
				SpawnInfo =
				{
					classname = "material_modify_control"
					materialName = "models/props_gdef/turret/laser_power_light"
					materialVar = "$HeatAmount"
					parentname = "laser_turret_base"
					targetname = "laser_turret_heattexture"
					origin = Vector( 3, -34, 9.25002 )
				}
			}
			laser_turret_heat_effect = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 120, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "steam_short"
					parentname = "laser_turret_base"
					render_in_front = "0"
					start_active = "0"
					targetname = "laser_turret_heat_effect"
					origin = Vector( 8, 9, 16 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // TurretsystemLaserTurret

RegisterEntityGroup( "TurretsystemLaserTurret", TurretsystemLaserTurret )
