//-------------------------------------------------------
// Autogenerated from 'turretsystem_flak_turret.vmf'
//-------------------------------------------------------
TurretsystemFlakTurret <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.flak_turret_traverse,
			EntityGroup.SpawnTables.flak_turret_gun,
			EntityGroup.SpawnTables.flak_turret_base,
			EntityGroup.SpawnTables.flak_turret_comp,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.flak_turret_hit_target,
			EntityGroup.SpawnTables.flak_turret_shell_effect,
			EntityGroup.SpawnTables.flak_turret_tracer,
			EntityGroup.SpawnTables.flak_turret_muzzleflash,
			EntityGroup.SpawnTables.flak_turret_gun,
			EntityGroup.SpawnTables.flak_turret_comp,
			EntityGroup.SpawnTables.flak_turret_heattexture,
			EntityGroup.SpawnTables.flak_turret_traverse,
			EntityGroup.SpawnTables.flak_turret_shell_hurt,
			EntityGroup.SpawnTables.flak_turret_casing,
			EntityGroup.SpawnTables.flak_turret_comp_use,
			EntityGroup.SpawnTables.flak_turret_base,
			EntityGroup.SpawnTables.flak_turret_heat_effect,
			EntityGroup.SpawnTables.flak_turret_tracer_target,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			flak_turret_heattexture = 
			{
				SpawnInfo =
				{
					classname = "material_modify_control"
					materialName = "models/props_gdef/turret/50cal_heat"
					materialVar = "$HeatAmount"
					parentname = "flak_turret_gun"
					targetname = "flak_turret_heattexture"
					origin = Vector( 7.78601, -32, 9.25002 )
				}
			}
			flak_turret_traverse = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/turret_traverse.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flak_turret_traverse"
					origin = Vector( 0, 0, 32.1 )
				}
			}
			flak_turret_gun = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					DefaultAnim = "idle"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/turret_gun.mdl"
					parentname = "flak_turret_traverse"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flak_turret_gun"
					vscripts = "turretsystem_turret_flak"
					origin = Vector( -1, 0, 42.7 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "flak_turret_traverseKill0-1"
							cmd2 = "flak_turret_baseKill0-1"
							cmd3 = "flak_turret_heattextureKill0-1"
							cmd4 = "flak_turret_tracerKill0-1"
							cmd5 = "flak_turret_muzzleflashKill0-1"
							cmd6 = "flak_turret_tracer_targetKill0-1"
							cmd7 = "flak_turret_shell_effectKill0-1"
							cmd8 = "flak_turret_shell_hurtKill0-1"
							cmd9 = "flak_turret_heat_effectKill0-1"
							cmd10 = "flak_turret_comp_useKill0-1"
							cmd11 = "!selfKill0-1"
							cmd12 = "flak_turret_compKill0-1"
						}
					}
				}
			}
			flak_turret_base = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/turret/turret_base.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "flak_turret_base"
					origin = Vector( 0, 0, 0 )
				}
			}
			flak_turret_muzzleflash = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "weapon_muzzle_flash_50cal"
					parentname = "flak_turret_gun"
					render_in_front = "0"
					start_active = "0"
					targetname = "flak_turret_muzzleflash"
					origin = Vector( 52, -0.113007, 45.3 )
				}
			}
			flak_turret_tracer = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1 = "flak_turret_tracer_target"
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "weapon_tracers_explosive"
					parentname = "flak_turret_gun"
					render_in_front = "0"
					start_active = "0"
					targetname = "flak_turret_tracer"
					origin = Vector( 53, -0.113007, 45.3 )
				}
			}
			flak_turret_heat_effect = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "minigun_overheat_smoke"
					parentname = "flak_turret_gun"
					render_in_front = "0"
					start_active = "0"
					targetname = "flak_turret_heat_effect"
					origin = Vector( 49, -0.113007, 45.3 )
				}
			}
			flak_turret_comp = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 10, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "32"
					glowstate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/laptop/laptop.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "3"
					solid = "6"
					targetname = "flak_turret_comp"
					origin = Vector( -1, -13.413, 0.250031 )
				}
			}
			flak_turret_comp_use = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "flak_turret_comp"
					origin = Vector( -12.28, -16.13, 8.25 )
					targetname = "flak_turret_comp_use"
					vscripts = "usetargets/turretsystem_turret_flak_comp"
				}
			}
			flak_turret_tracer_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					parentname = "flak_turret_hit_target"
					targetname = "flak_turret_tracer_target"
					origin = Vector( 112, -0.412994, 45.25 )
				}
			}
			flak_turret_shell_effect = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_explosive_ammo_large"
					parentname = "flak_turret_hit_target"
					render_in_front = "0"
					start_active = "0"
					targetname = "flak_turret_shell_effect"
					origin = Vector( 112, -0.113007, 45.25 )
				}
			}
			flak_turret_shell_hurt = 
			{
				SpawnInfo =
				{
					classname = "point_hurt"
					Damage = "150"
					DamageDelay = "1"
					DamageRadius = "50"
					DamageType = "-2147483646"
					targetname = "flak_turret_shell_hurt"
					origin = Vector( 112, -0.113007, 45.25 )
				}
			}
			flak_turret_hit_target = 
			{
				SpawnInfo =
				{
					classname = "info_target_instructor_hint"
					targetname = "flak_turret_hit_target"
					origin = Vector( 112, -0.113007, 45.25 )
				}
			}
			flak_turret_casing = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 270, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "weapon_shell_casing_50cal"
					parentname = "flak_turret_gun"
					render_in_front = "0"
					start_active = "0"
					targetname = "flak_turret_casing"
					origin = Vector( -1, -4, 44.5 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // TurretsystemFlakTurret

RegisterEntityGroup( "TurretsystemFlakTurret", TurretsystemFlakTurret )
