//-------------------------------------------------------
// Autogenerated from 'gdef_barricade_build.vmf'
//-------------------------------------------------------
GdefBarricadeBuild <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.barricade_build,
			EntityGroup.SpawnTables.barricade_materials,
			EntityGroup.SpawnTables.barricade_break,
			EntityGroup.SpawnTables.barricade_frame,
			EntityGroup.SpawnTables.exclusion_zone_woodpile,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.gdef_barricade_hint,
			EntityGroup.SpawnTables.exclusion_zone_woodpile,
			EntityGroup.SpawnTables.barricade_build_use,
			EntityGroup.SpawnTables.barricade_build_maker,
			EntityGroup.SpawnTables.barricade_build_particle,
			EntityGroup.SpawnTables.barricade_build,
			EntityGroup.SpawnTables.barricade_template,
			EntityGroup.SpawnTables.barricade_materials_template,
			EntityGroup.SpawnTables.barricade_build_sound,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			barricade_build = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, 0 )
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 255"
					glowrange = "512"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_mill/wood_stack.mdl"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "barricade_build"
					updatechildren = "0"
					vscripts = "gdef_barricade_pile"
					origin = Vector( 0, 0, 0 )
				}
			}
			barricade_materials = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_override"
					angles = Vector( 0, 180, 0 )
					damagetoenablemotion = "0"
					Damagetype = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowstate = "0"
					health = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_gdef/barricade_materials.mdl"
					nodamageforces = "0"
					physdamagescale = "0.1"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "41216"
					targetname = "barricade_materials"
					origin = Vector( 96, -4.19629e-006, 5 )
					connections =
					{
						OnUser2 =
						{
							cmd1 = "barricade_spawnerSetParent0-1"
						}
						OnUser1 =
						{
							cmd1 = "barricade_materials_useKill0.1-1"
							cmd2 = "barricade_spawnerKill0.1-1"
							cmd3 = "!selfKill0.1-1"
							cmd4 = "barricade_spawnerForceSpawn0-1"
							cmd5 = "barricade_materials_particleStart0-1"
							cmd6 = "barricade_materials_particleKill10-1"
						}
						OnPhysGunDrop =
						{
							cmd1 = "!selfRunScriptCodeg_ModeScript.CrateDropped()0-1"
						}
					}
				}
			}
			barricade_break = 
			{
				SpawnInfo =
				{
					classname = "prop_wall_breakable"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					model = "models/props_buildables/plank_barricade01.mdl"
					skin = "0"
					spawnflags = "0"
					targetname = "barricade_break"
					origin = Vector( -128, 5.59506e-006, 9.00002 )
					connections =
					{
						OnBreak =
						{
							cmd1 = "barricade_break_counterAdd10-1"
						}
						OnKilled =
						{
							cmd1 = "barricade_break_counterSetValue60-1"
						}
					}
				}
			}
			barricade_frame = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/barricade_side.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "barricade_frame"
					origin = Vector( -123, 5.3765e-006, 0 )
				}
			}
			barricade_materials_use = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "barricade_materials"
					origin = Vector( 72, 0, 0 )
					targetname = "barricade_materials_use"
					thinkfunction = "Think"
					vscripts = "usetargets/barricade_build"
				}
			}
			barricade_spawner = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "barricade_template"
					parentname = "barricade_materials"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					spawnflags = "0"
					targetname = "barricade_spawner"
					origin = Vector( 96, -4.19629e-006, 5 )
				}
			}
			barricade_materials_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "0"
					targetname = "barricade_materials_template"
					Template01 = "barricade_materials"
					Template02 = "barricade_materials_use"
					Template03 = "barricade_materials_particle"
					Template04 = "barricade_spawner"
					origin = Vector( 96, -8, 0 )
				}
			}
			barricade_materials_particle = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 270, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "small_smoke"
					parentname = "barricade_materials"
					render_in_front = "0"
					start_active = "0"
					targetname = "barricade_materials_particle"
					origin = Vector( 96, -4.19629e-006, 5 )
				}
			}
			barricade_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "0"
					targetname = "barricade_template"
					Template01 = "barricade_break"
					Template02 = "barricade_frame"
					Template04 = "barricade_relay"
					Template05 = "barricade_break_counter"
					origin = Vector( -126, 5.50763e-006, 5 )
				}
			}
			barricade_build_particle = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 180, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "small_smoke"
					render_in_front = "0"
					start_active = "0"
					targetname = "barricade_build_particle"
					origin = Vector( -1, -3, 36.8006 )
				}
			}
			barricade_build_maker = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "barricade_materials_template"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0.15"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "barricade_build_maker"
					origin = Vector( -1, -3, 32 )
				}
			}
			barricade_build_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "ui/gift_drop.wav"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "barricade_build"
					spawnflags = "48"
					targetname = "barricade_build_sound"
					origin = Vector( -2, -40, 43 )
				}
			}
			barricade_build_use = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "barricade_build"
					origin = Vector( 7.48, 23, 34.8 )
					targetname = "barricade_build_use"
					vscripts = "usetargets/barricade_stack"
					connections =
					{
						OnUseCanceled =
						{
							cmd1 = "!selfFireUser10-1"
						}
						OnUseFinished =
						{
							cmd1 = "barricade_build_makerForceSpawn0-1"
							cmd2 = "barricade_build_soundPlaySound0-1"
							cmd3 = "barricade_build_particleStart0-1"
							cmd4 = "barricade_build_particleStop2-1"
							cmd5 = "gdef_barricade_hintEndHint0-1"
						}
						OnUser1 =
						{
							cmd1 = "barricade_build_useRunScriptCodeEnableUse()0-1"
							cmd2 = "barricade_build_useRunScriptCodeTurnOn()0-1"
						}
					}
				}
			}
			gdef_barricade_hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_auto_start = "1"
					hint_caption = "Pick up materials to build barricades"
					hint_color = "255 255 255"
					hint_display_limit = "1"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_info"
					hint_icon_offset = "16"
					hint_icon_onscreen = "icon_info"
					hint_instance_type = "0"
					hint_name = "gdef_hint"
					hint_range = "0"
					hint_target = "barricade_build"
					hint_timeout = "10"
					targetname = "gdef_barricade_hint"
					origin = Vector( 2, 50, 38 )
				}
			}
			barricade_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "barricade_relay"
					origin = Vector( -111, 14.5356, 22.4344 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "!selfKill0.02-1"
							cmd2 = "!selfRunScriptCodeg_ModeScript.BarricadeBuilt()0-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 29.1346, -54.7957, 9 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "barricade_buildStartGlowing0-1"
						}
					}
				}
			}
			barricade_break_counter = 
			{
				SpawnInfo =
				{
					classname = "math_counter"
					max = "6"
					min = "0"
					startvalue = "0"
					targetname = "barricade_break_counter"
					origin = Vector( -108, -15, 22.4344 )
					connections =
					{
						OnHitMax =
						{
							cmd1 = "barricade_frameBreak0-1"
							cmd2 = "barricade_breakKill0-1"
						}
					}
				}
			}
			exclusion_zone_woodpile = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					disablereceiveshadows = "1"
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_gdef/exclusion_zone_woodpile.mdl"
					renderamt = "255"
					rendercolor = "255 0 0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "exclusion_zone_woodpile"
					origin = Vector( 0, -5, 29 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // GdefBarricadeBuild

RegisterEntityGroup( "GdefBarricadeBuild", GdefBarricadeBuild )
